### PR TITLE
Implement client-side pagination

### PR DESCRIPTION
**Pull request by matthewstrasiotto**
This aims to address #21 , though is unlikely to address client side performance issues without the help of #51 . 

Personally I think that between #51 & this, the problem of (relatively) efficiently rendering the content-view is addressed. 

Client-side pagination is NOT the best solution for the list-view, but I chose it because I'd already implemented it for the content-view.

### CODE REVIEW

**Comment by mstr3336** [comment]
Friendly nudge @MLanghof

**Comment by MLanghof** [comment]
Ok, a lot has happened, and I'm not sure which PRs should or shouldn't be merged in which order.

Do I understand correctly that this is more or less outdated in face of #53? Maybe you could give a brief overview over how you'd like to proceed?

**Comment by matthewstrasiotto** [comment]
This came first, and was a first attempt. I was more comfortable with it than server side pagination, but really it can be closed

**Comment by matthewstrasiotto** [comment]
> Ok, a lot has happened, and I'm not sure which PRs should or shouldn't be merged in which order.

I've marked each PR that shouldn't be merged as draft. 

Every non-draft PR should be more or less independent, and can be merged in whatever order, though it probably makes the most sense to merge them from oldest to newest.

I'd appreciate the most thorough review of #53 , since that was furthest from my comfort zone, and the most complex 

#56 uses jQuery selectors that refer to content from #55 , so there's no value in merging #56 before #55 .

**Pull request closed without merging**
